version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: finatext
      MYSQL_USER: finatext_user
      MYSQL_PASSWORD: finatexts69294
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: finatext
      MYSQL_USER: finatext_user
      MYSQL_PASSWORD: finatexts69294
    volumes:
      - ./create_table.sql:/docker-entrypoint-initdb.d/create_table.sql